### ISSUE TITLE
App crashes if Identity is using incompatible uid

### ISSUE THREAD

**Issue by stefandevo** [inthehand/InTheHand.AppCenter.Insights#2]
Maybe you can add some checking on the Identify method.
The first parameter seems that have a constraint in AppCenter that Insights did not have.

[AppCenter] ERROR: -[MSCustomProperties isValidKey:]/65 Custom property "Unique ID" must match "^[a-zA-Z][a-zA-Z0-9]*$"

And then we get a crash. Once you have this, the app is not starting, because it crashes immediately...

In my case it was a name of a user (which contained spaces).

**Comment by peterfoot** [comment]
Fixed in 1.5.0.0316. The problem was the key name used internally and not the contents of the uid argument
